
name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow when a new tag starting with 'v' is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-app:$GITHUB_SHA .
          docker tag my-app:$GITHUB_SHA ghcr.io/rapture1976/my-app:$GITHUB_SHA  # Replace 'your-username'

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/your-username/my-app:$GITHUB_SHA  # Replace 'your-username'

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure GITHUB_TOKEN has appropriate permissions
