
name: Build and Release

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-app:${{ github.sha }} .
          docker tag my-app:${{ github.sha }} ghcr.io/rapture1976/my-app:${{ github.sha }}

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/rapture1976/my-app:${{ github.sha }}

      - name: Create a tag
        id: create_tag
        run: |
          VERSION=v1.$(date +'%Y%m%d%H%M%S')  # Create a timestamped tag
          echo "Generated tag: $VERSION"
          echo "tag=$VERSION" >> $GITHUB_ENV  # Export the tag for use in later steps

      - name: Push tag
        uses: pfrank/auto-tag-action@v1  # Automatically creates and pushes the tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.tag }}

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
